# docker-compose.yml
version: "3.3"

networks:
    microservice:
      external: true
      
services: 
    laracom-user-service:
        depends_on:
            - laracom-user-db
            - laracom-nats
        build: ./user-service
        ports:
            - 9092:9091
        environment:
            MICRO_SERVER_ADDRESS: ":9091"
            MICRO_REGISTRY: "etcd"
            MICRO_REGISTRY_ADDRESS: "laracom-etcd:2379"
            MICRO_BROKER: "nats"
            MICRO_BROKER_ADDRESS: "laracom-nats:4222"
            DB_HOST: "laracom-user-db:3306"
            DB_NAME: "laracom_user"
            DB_USER: "test"
            DB_PASSWORD: "test"
        networks:
            - microservice
    laracom-product-service:
        depends_on:
            - laracom-product-db
        build: ./product-service
        ports:
            - 9093:9091
        environment:
            MICRO_SERVER_ADDRESS: ":9091"
            MICRO_REGISTRY: "etcd"
            MICRO_REGISTRY_ADDRESS: "laracom-etcd:2379"
            DB_HOST: "laracom-product-db:3306"
            DB_NAME: "laracom_product"
            DB_USER: "product"
            DB_PASSWORD: "test"
        networks:
            - microservice

    laracom-micro-api:
        image: microhq/micro:latest
        environment:
            MICRO_REGISTRY: "etcd"
            MICRO_REGISTRY_ADDRESS: "laracom-etcd:2379"
        links:
            - laracom-user-service
            - laracom-product-service
        ports:
            - 8080:8080
        networks:
            - microservice
        command: api --handler=rpc --namespace=laracom.service
        
    laracom-web-dashboard:
        image: microhq/micro:latest
        container_name: laracom-web-dashboard
        environment:
            MICRO_REGISTRY: "etcd"
            MICRO_REGISTRY_ADDRESS: "laracom-etcd:2379"
        links:
            - laracom-user-service
            - laracom-product-service
        ports:
            - 8082:8082
        networks:
            - microservice
        command: web

    laracom-user-db:
        image: mysql:5.7
        container_name: laracom-user-db
        ports:
            - 33066:3306
        volumes:
            - db_user_data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_USER: "test"
            MYSQL_PASSWORD: "test"
            MYSQL_DATABASE: "laracom_user"
            MYSQL_ROOT_PASSWORD: "root"
        networks:
            - microservice

    laracom-product-db:
        image: mysql:5.7
        ports:
            - 33067:3306
        volumes:
            - db_product_data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_USER: "product"
            MYSQL_PASSWORD: "test"
            MYSQL_DATABASE: "laracom_product"
            MYSQL_ROOT_PASSWORD: "root"
        networks:
            - microservice

    laracom-nats:
        image: nats:latest
        ports:
            - 4222:4222
        restart: always
        networks:
            - microservice

    laracom-etcd:
        image: bitnami/etcd:latest
        environment:
            ALLOW_NONE_AUTHENTICATION: "yes"
            ETCD_ADVERTISE_CLIENT_URLS: "http://laracom-etcd:2379"
        ports:
            - 2379:2379
            - 2380:2380
        networks:
            - microservice
volumes:
    db_user_data: {}
    db_product_data: {}
